In [1]:
#the neccesary library 
import pyreadstat

import pandas as pd

In [3]:
# Define the file paths for the .sav and .csv files
input_file = "year1.sav"


data, metadata = pyreadstat.read_sav(input_file)

# Convert the data to a pandas dataframe
df = pd.DataFrame(data)

# Save the data to a CSV file
output_file = "year1.csv"
df.to_csv(output_file, index=False)

In [7]:
# Define the file paths for the .sav and .csv files
input_file = "year2.sav"


data, metadata = pyreadstat.read_sav(input_file)

# Convert the data to a pandas dataframe
df = pd.DataFrame(data)

# Save the data to a CSV file
output_file = "year2.csv"
df.to_csv(output_file, index=False)

In [8]:
# Define the file paths for the .sav and .csv files
input_file = "year3.sav"


data, metadata = pyreadstat.read_sav(input_file)

# Convert the data to a pandas dataframe
df = pd.DataFrame(data)

# Save the data to a CSV file
output_file = "year3.csv"
df.to_csv(output_file, index=False)

In [9]:
# Define the file paths for the .sav and .csv files
input_file = "year4.sav"


data, metadata = pyreadstat.read_sav(input_file)

# Convert the data to a pandas dataframe
df = pd.DataFrame(data)

# Save the data to a CSV file
output_file = "year4.csv"
df.to_csv(output_file, index=False)

In [10]:
# Define the file paths for the .sav and .csv files
input_file = "year5.sav"


data, metadata = pyreadstat.read_sav(input_file)

# Convert the data to a pandas dataframe
df = pd.DataFrame(data)

# Save the data to a CSV file
output_file = "year5.csv"
df.to_csv(output_file, index=False)

In [11]:
# Define the file paths for the .sav and .csv files
input_file = "year6.sav"


data, metadata = pyreadstat.read_sav(input_file)

# Convert the data to a pandas dataframe
df = pd.DataFrame(data)

# Save the data to a CSV file
output_file = "year6.csv"
df.to_csv(output_file, index=False)

In [ ]:
# Read the CSV file
year1 = pd.read_csv("year1.csv")
year2 = pd.read_csv("year2.csv")
year3 = pd.read_csv("year3.csv")
year4 = pd.read_csv("year4.csv")
year5 = pd.read_csv("year5.csv")
year6 = pd.read_csv("year6.csv")

In [2]:
year1 = pd.read_csv("year1.csv")

In [4]:
year1

,serial,mode,QuVer,group,Type,Month,Quarter,Overall,age16plus,age19plus,...,days10pGR4x_RUGBYLEAGUE_F04,days10pGR4x_SWIM_L01,days10pGR4x_TABLETENNIS_G03,days10pGR8x_ROWING_H06,days10pGR8x_ROWMACHINE_P13,days10pGR8x_TAEKWONDO_J05,days10pGR8x_WEIGHTLIFTING_P19,Months_12_EXBIKE_CYCLECLASS_D04,Months_12_NOT4x_CYCALL_C02,Months_12_NOT4x_EXBIKE_CYCLECLASS_D04
0,1.604801e+14,2.0,1.0,NaN,1.0,7.0,3.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.511600e+14,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0
2,1.511600e+14,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.511600e+14,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.511600e+14,2.0,1.0,NaN,1.0,2.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201574,1.610903e+14,1.0,2.0,2.0,1.0,12.0,4.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
201575,1.610903e+14,2.0,2.0,NaN,1.0,12.0,4.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
201576,1.610903e+14,2.0,2.0,NaN,1.0,12.0,4.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
201577,1.610903e+14,1.0,2.0,2.0,1.0,12.0,4.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
201578,1.610903e+14,2.0,2.0,NaN,1.0,12.0,4.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
filename = "year2.csv"
chunksize = 10 ** 6

for chunk in pd.read_csv(filename, chunksize=chunksize):
    # chunk is a DataFrame. To "process" the rows in the chunk:
    for index, row in chunk.iterrows():
        print(row)

KeyboardInterrupt: